version: "3.5"

services:
    postgres:
        container_name: postgres_financas
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - postgres
        restart: unless-stopped
    cache:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
networks:
    default:
        driver: bridge
    postgres:
        driver: bridge

volumes:
    postgres:
    cache:
        driver: local